version: '3'

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: asn007/rustdesk-server:latest
    build:
      context: .
    command: hbbs -r 45.8.97.46:21117 -k _
    volumes:
      - ./data:/opt/run
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    build:
      context: .
    ports:
      - 21117:21117
      - 21119:21119
    image: asn007/rustdesk-server:latest
    command: hbbr -k _
    volumes:
      - ./data:/opt/run
    restart: unless-stopped
